import { Plant, PlantCategory, LightRequirement, FoliageType, SoilType } from './types';

export const plants: Plant[] = [
  // LIST 1: Flowers and Perennials
  {
    id: "primrose",
    name: "Primrose",
    scientificName: "Primula vulgaris",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "15 cm × 15 cm",
    appearance: "Pale yellow flowers above rosettes of crinkled green leaves",
    conditions: "Partial shade, moist but well-drained compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Early nectar source for bees and hoverflies"
  },
  {
    id: "feverfew",
    name: "Feverfew",
    scientificName: "Tanacetum parthenium",
    category: PlantCategory.FlowersPerennials,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "60 cm × 80 cm",
    appearance: "Clusters of small, white daisy-like flowers",
    conditions: "Full sun and free-draining soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Attracts pollinators and can deter certain pests"
  },
  {
    id: "st-johns-wort",
    name: "Perforate St John’s Wort",
    scientificName: "Hypericum perforatum",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "1 m × 60 cm",
    appearance: "Yellow star-shaped flowers with dotted petals",
    conditions: "Sunny, well-drained soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Supports bees and butterflies"
  },
  {
    id: "honeysuckle-shrub",
    name: "Honeysuckle",
    scientificName: "Lonicera periclymenum",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "Up to 3 m × 4 m (smaller if pruned)",
    appearance: "Creamy-yellow and pink, strongly scented blooms",
    conditions: "Sunny stems, shaded roots; moist but well-drained soil",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Important nectar source for moths and nesting cover for birds"
  },
  {
    id: "thrift",
    name: "Thrift",
    scientificName: "Armeria maritima",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "20 cm × 30 cm",
    appearance: "Grass-like tufts with bright pink flower heads",
    conditions: "Full sun and free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Gritty],
    ecologicalImportance: "Supports coastal pollinators"
  },
  {
    id: "birds-foot-trefoil",
    name: "Bird’s-foot Trefoil",
    scientificName: "Lotus corniculatus",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "50 cm × 50 cm",
    appearance: "Yellow pea-like flowers, later seed pods shaped like a bird’s foot",
    conditions: "Sunny and well-drained, even on poor soils",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Larval food plant for Common Blue butterflies"
  },
  {
    id: "harebell",
    name: "Harebell",
    scientificName: "Campanula rotundifolia",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "30 cm × 30 cm",
    appearance: "Slender stems with delicate blue, bell-shaped flowers",
    conditions: "Full sun or light shade, well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Provides nectar for bees and hoverflies"
  },
  {
    id: "foxglove",
    name: "Foxglove",
    scientificName: "Digitalis purpurea",
    category: PlantCategory.FlowersPerennials,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Biennial,
    dimensions: "1.2 m × 45 cm",
    appearance: "Tall spires of purple-pink tubular flowers",
    conditions: "Moist, semi-shaded compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Rich nectar source for long-tongued bees"
  },
  {
    id: "coral-bells",
    name: "Coral Bells",
    scientificName: "Heuchera spp.",
    category: PlantCategory.FlowersPerennials,
    native: false,
    nativeDetails: "No, North American origin",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "20–40cm × 30–40cm",
    appearance: "Colourful foliage and delicate flower sprays",
    conditions: "Partial shade, moist but well-drained compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Attracts pollinators such as bees and butterflies"
  },

  // LIST 2: Herbs
  {
    id: "sage",
    name: "Sage",
    scientificName: "Salvia officinalis",
    category: PlantCategory.Herbs,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "60 cm × 60 cm",
    appearance: "Grey-green aromatic leaves with pale blue flowers",
    conditions: "Full sun, gritty well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Gritty, SoilType.WellDrained],
    ecologicalImportance: "Excellent for pollinators, especially bees"
  },
  {
    id: "rosemary",
    name: "Rosemary",
    scientificName: "Salvia rosmarinus",
    category: PlantCategory.Herbs,
    native: false,
    nativeDetails: "No – Mediterranean native",
    foliage: FoliageType.Evergreen,
    dimensions: "1 m × 1 m",
    appearance: "Needle-like leaves and pale blue flowers",
    conditions: "Full sun, free-draining soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Early nectar for bees in spring"
  },
  {
    id: "lavender",
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    category: PlantCategory.Herbs,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "60 cm × 80 cm",
    appearance: "Silver foliage and purple flower spikes",
    conditions: "Full sun, well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Supports bees, butterflies, and hoverflies"
  },
  {
    id: "wild-marjoram",
    name: "Wild Marjoram",
    scientificName: "Origanum vulgare",
    category: PlantCategory.Herbs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "40 cm × 40 cm",
    appearance: "Small, aromatic leaves with pink-purple summer flowers",
    conditions: "Full sun, well-drained soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Attracts butterflies and many beneficial insects"
  },
  {
    id: "thyme",
    name: "Thyme",
    scientificName: "Thymus vulgaris",
    category: PlantCategory.Herbs,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "20 cm × 30 cm",
    appearance: "Small grey-green leaves and pink flowers",
    conditions: "Full sun, dry well-drained soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Gritty, SoilType.WellDrained],
    ecologicalImportance: "Excellent for bees and low-growing wildlife habitats"
  },
  {
    id: "mint",
    name: "Mint",
    scientificName: "Mentha spicata / Mentha × piperita",
    category: PlantCategory.Herbs,
    native: true,
    nativeDetails: "Partly (some species native)",
    foliage: FoliageType.Deciduous,
    dimensions: "60 cm × spreading",
    appearance: "Fragrant green leaves and lilac flower spikes",
    conditions: "Moist soil in sun or partial shade",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Supports hoverflies, bees, and other pollinators"
  },

  // LIST 3: Shrubs
  {
    id: "box",
    name: "Box",
    scientificName: "Buxus sempervirens",
    category: PlantCategory.Shrubs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "1.5 m × 1.5 m (pruned)",
    appearance: "Small glossy leaves; dense growth",
    conditions: "Sun or shade, well-drained soil",
    lightTags: [LightRequirement.Sun, LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Shelter for insects and nesting birds"
  },
  {
    id: "holly",
    name: "Holly",
    scientificName: "Ilex aquifolium",
    category: PlantCategory.Shrubs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "Variable, easily pruned",
    appearance: "Glossy, spiny leaves with red berries",
    conditions: "Tolerant of shade and varied soils",
    lightTags: [LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained, SoilType.Moist],
    ecologicalImportance: "Nectar, berries, and cover for birds"
  },
  {
    id: "dogwood",
    name: "Dogwood",
    scientificName: "Cornus sanguinea",
    category: PlantCategory.Shrubs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "2 m × 2 m",
    appearance: "Red winter stems and white summer flowers",
    conditions: "Full sun, moist but well-drained soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Supports pollinators and provides bird food"
  },
  {
    id: "hazel",
    name: "Hazel",
    scientificName: "Corylus avellana",
    category: PlantCategory.Shrubs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "Up to 3 m × 3 m in containers",
    appearance: "Rounded leaves and yellow catkins in spring",
    conditions: "Sun or light shade, fertile compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile],
    ecologicalImportance: "Nuts for wildlife, supports many moths"
  },
  {
    id: "hawthorn",
    name: "Hawthorn",
    scientificName: "Crataegus monogyna",
    category: PlantCategory.Shrubs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "3–4 m × 3 m",
    appearance: "White spring blossom and red autumn haws",
    conditions: "Sun or partial shade, well-drained soil",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Nectar for insects, berries for birds"
  },
  {
    id: "elder",
    name: "Elder",
    scientificName: "Sambucus nigra",
    category: PlantCategory.Shrubs,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "Up to 4 m × 3 m",
    appearance: "Creamy flowers followed by dark purple berries",
    conditions: "Full sun or partial shade",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Food for pollinators and birds"
  },
  {
    id: "skimmia",
    name: "Skimmia",
    scientificName: "Skimmia japonica",
    category: PlantCategory.Shrubs,
    native: false,
    nativeDetails: "No – East Asian origin",
    foliage: FoliageType.Evergreen,
    dimensions: "1 m × 1 m",
    appearance: "Glossy leaves, fragrant flowers, and red berries",
    conditions: "Shade or semi-shade, moist compost",
    lightTags: [LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Early pollen and berries for birds"
  },
  {
    id: "shrubby-cinquefoil",
    name: "Shrubby Cinquefoil",
    scientificName: "Potentilla fruticosa",
    category: PlantCategory.Shrubs,
    native: false,
    nativeDetails: "No – northern hemisphere origin",
    foliage: FoliageType.Deciduous,
    dimensions: "1 m × 1 m",
    appearance: "Compact shrub with yellow or pink flowers",
    conditions: "Full sun, well-drained soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Long flowering season supporting pollinators"
  },
  {
    id: "dwarf-rhododendron",
    name: "Dwarf Rhododendron",
    scientificName: "Rhododendron ‘Dora Amateis’",
    category: PlantCategory.Shrubs,
    native: false,
    nativeDetails: "No, hybrid origin",
    foliage: FoliageType.Evergreen,
    dimensions: "40–60cm × 60cm",
    appearance: "Compact growth, white or pink flowers",
    conditions: "Partial shade; use ericaceous compost for acidity",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Ericaceous, SoilType.Moist],
    ecologicalImportance: "Early spring flowers provide nectar for pollinators such as bees and bumblebees"
  },

  // LIST 4: Small Trees
  {
    id: "olive",
    name: "Olive",
    scientificName: "Olea europaea",
    category: PlantCategory.SmallTrees,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "2–3 m × 2 m",
    appearance: "Narrow, grey-green leaves; gnarled trunk with age",
    conditions: "Full sun, free-draining soil; protect from frost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Provides shelter and pollen for insects in warm conditions"
  },
  {
    id: "crab-apple",
    name: "Crab Apple",
    scientificName: "Malus sylvestris",
    category: PlantCategory.SmallTrees,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "2–3 m × 2 m",
    appearance: "White to pink spring blossom, small autumn fruits",
    conditions: "Full sun, fertile soil, regular watering",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.Moist],
    ecologicalImportance: "Blossom supports pollinators; fruits feed birds and mammals"
  },
  {
    id: "rowan",
    name: "Rowan",
    scientificName: "Sorbus aucuparia",
    category: PlantCategory.SmallTrees,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "3–5 m × 3 m (large container)",
    appearance: "White flowers in spring, red or orange berries in autumn",
    conditions: "Full sun or light shade; moist, well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Vital for pollinators, birds, and insects"
  },
  {
    id: "star-magnolia",
    name: "Star Magnolia",
    scientificName: "Magnolia stellata",
    category: PlantCategory.SmallTrees,
    native: false,
    nativeDetails: "No – Japan",
    foliage: FoliageType.Deciduous,
    dimensions: "2–3 m × 2 m",
    appearance: "White, star-shaped flowers in early spring",
    conditions: "Sheltered, partially shaded site with acidic compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Ericaceous],
    ecologicalImportance: "Early-season nectar for pollinators"
  },
  {
    id: "italian-cypress",
    name: "Italian Cypress ‘Wilma’",
    scientificName: "Cupressus sempervirens",
    category: PlantCategory.SmallTrees,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "2–3 m tall, narrow habit",
    appearance: "Upright, columnar shape with bright green foliage",
    conditions: "Full sun, well-drained compost; protect from drying winds",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Shelter and nesting structure for small birds"
  },
  {
    id: "bay-tree",
    name: "Bay Tree / Sweet Bay",
    scientificName: "Laurus nobilis",
    category: PlantCategory.SmallTrees,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Evergreen,
    dimensions: "1.5–2 m × 1 m (trained form)",
    appearance: "Glossy aromatic leaves",
    conditions: "Sun or partial shade; well-drained soil",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Nectar and habitat for pollinators"
  },
  {
    id: "common-beech",
    name: "Common Beech",
    scientificName: "Fagus sylvatica",
    category: PlantCategory.SmallTrees,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "Variable with pruning",
    appearance: "Glossy green foliage turning copper in autumn",
    conditions: "Well-drained soil, sunny spot",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Supports numerous insects and provides shelter"
  },
  {
    id: "amelanchier",
    name: "Amelanchier",
    scientificName: "Amelanchier canadensis",
    category: PlantCategory.SmallTrees,
    native: false,
    nativeDetails: "No – North America",
    foliage: FoliageType.Deciduous,
    dimensions: "2–3 m × 2 m",
    appearance: "White spring flowers, red berries, and good autumn colour",
    conditions: "Full sun or partial shade; moist compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Nectar, berries, and shelter for wildlife"
  },
  {
    id: "paperbark-maple",
    name: "Paperbark Maple",
    scientificName: "Acer griseum",
    category: PlantCategory.SmallTrees,
    native: false,
    nativeDetails: "No – China",
    foliage: FoliageType.Deciduous,
    dimensions: "3 m × 2 m",
    appearance: "Peeling copper bark and fiery autumn foliage",
    conditions: "Sheltered, sunny or lightly shaded site; fertile compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile],
    ecologicalImportance: "Provides autumn pollen and bark habitat for insects"
  },
  {
    id: "field-maple",
    name: "Field Maple",
    scientificName: "Acer campestre",
    category: PlantCategory.SmallTrees,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "3–4 m × 3 m (compact form in container)",
    appearance: "Rounded leaves turning golden in autumn",
    conditions: "Full sun or partial shade; adaptable to soil types",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Native host to aphids, caterpillars, and many birds"
  },
  {
    id: "bird-cherry",
    name: "Bird Cherry",
    scientificName: "Prunus padus",
    category: PlantCategory.SmallTrees,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "3–5 m × 3 m (small tree form)",
    appearance: "Racemes of fragrant white flowers in spring",
    conditions: "Moist, well-drained soil in sun or partial shade",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Supports pollinators, birds, and caterpillars"
  },

  // LIST 6: Grasses
  {
    id: "tufted-hair-grass",
    name: "Tufted Hair Grass",
    scientificName: "Deschampsia cespitosa",
    category: PlantCategory.Grasses,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "60–120 cm × 60 cm",
    appearance: "Fine green foliage with airy golden flower heads",
    conditions: "Sun or partial shade; moist but well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Provides seed and shelter for insects and small birds"
  },
  {
    id: "blue-fescue",
    name: "Blue Fescue",
    scientificName: "Festuca glauca",
    category: PlantCategory.Grasses,
    native: false,
    nativeDetails: "No – European origin",
    foliage: FoliageType.Evergreen,
    dimensions: "25 cm × 30 cm",
    appearance: "Compact mounds of silvery-blue foliage with fine flower spikes",
    conditions: "Full sun; well-drained, gritty compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Gritty],
    ecologicalImportance: "Drought-tolerant; supports insects in dry conditions"
  },
  {
    id: "greater-woodrush",
    name: "Greater Woodrush",
    scientificName: "Luzula sylvatica",
    category: PlantCategory.Grasses,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "40 cm × 60 cm",
    appearance: "Glossy green tufts with brown flower spikes",
    conditions: "Shade or partial shade; moist soil",
    lightTags: [LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Valuable ground cover and refuge for woodland insects"
  },
  {
    id: "japanese-forest-grass",
    name: "Japanese Forest Grass",
    scientificName: "Hakonechloa macra",
    category: PlantCategory.Grasses,
    native: false,
    nativeDetails: "No – Japan",
    foliage: FoliageType.Deciduous,
    dimensions: "30–45 cm × 45 cm",
    appearance: "Graceful arching foliage in shades of green or gold",
    conditions: "Partial shade; moist, fertile compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.Fertile],
    ecologicalImportance: "Softens container edges; supports micro-invertebrates"
  },
  {
    id: "sweet-vernal-grass",
    name: "Sweet Vernal Grass",
    scientificName: "Anthoxanthum odoratum",
    category: PlantCategory.Grasses,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "30–40 cm × 30 cm",
    appearance: "Fine foliage with fragrant early flower heads",
    conditions: "Sun or partial shade; moderate moisture",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Early nectar and seed resource in naturalistic plantings"
  },
  {
    id: "japanese-sedge",
    name: "Japanese Sedge",
    scientificName: "Carex morrowii ‘Ice Dance’",
    category: PlantCategory.Grasses,
    native: false,
    nativeDetails: "No, Asian origin",
    foliage: FoliageType.Evergreen,
    dimensions: "30–45cm × 60cm",
    appearance: "Variegated green and white leaves",
    conditions: "Partial shade to shade; moist, well-drained soil",
    lightTags: [LightRequirement.PartialShade, LightRequirement.Shade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Offers shelter for small insects and other invertebrates and helps stabilise soil in shaded borders"
  },
  {
    id: "fountain-grass",
    name: "Fountain Grass",
    scientificName: "Pennisetum alopecuroides",
    category: PlantCategory.Grasses,
    native: false,
    nativeDetails: "No, Asian origin",
    foliage: FoliageType.Deciduous,
    dimensions: "60–90cm × 60cm",
    appearance: "Arching foliage with fluffy, bottlebrush flower heads",
    conditions: "Full sun; well-drained soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Provides late-season nectar for pollinators and seed for birds, adds structural diversity to naturalistic plantings"
  },

  // LIST 7: Ferns
  {
    id: "harts-tongue",
    name: "Hart’s-tongue Fern",
    scientificName: "Asplenium scolopendrium",
    category: PlantCategory.Ferns,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "30–60 cm × 45 cm",
    appearance: "Glossy, strap-like fronds",
    conditions: "Moist, shaded position in humus-rich compost",
    lightTags: [LightRequirement.Shade],
    soilTags: [SoilType.Moist, SoilType.Fertile],
    ecologicalImportance: "Provides shade habitat for insects and snails"
  },
  {
    id: "japanese-painted-fern",
    name: "Japanese Painted Fern",
    scientificName: "Athyrium niponicum",
    category: PlantCategory.Ferns,
    native: false,
    nativeDetails: "No – East Asia",
    foliage: FoliageType.Deciduous,
    dimensions: "45 cm × 60 cm",
    appearance: "Silvery-grey fronds with purple veins",
    conditions: "Moist, shaded compost; sheltered from wind",
    lightTags: [LightRequirement.Shade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Enhances shaded biodiversity microhabitats"
  },
  {
    id: "male-fern",
    name: "Male Fern",
    scientificName: "Dryopteris filix-mas",
    category: PlantCategory.Ferns,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "90 cm × 75 cm",
    appearance: "Upright, finely divided fronds",
    conditions: "Moist shade; woodland or north-facing sites",
    lightTags: [LightRequirement.Shade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Shelter for insects, small mammals, and amphibians"
  },
  {
    id: "soft-shield-fern",
    name: "Soft Shield Fern",
    scientificName: "Polystichum setiferum",
    category: PlantCategory.Ferns,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "60 cm × 60 cm",
    appearance: "Soft-textured, feathery green fronds",
    conditions: "Partial to full shade; moist soil",
    lightTags: [LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Adds structure and shelter to shaded containers"
  },

  // LIST 8: Succulents
  {
    id: "houseleek",
    name: "Houseleek",
    scientificName: "Sempervivum tectorum",
    category: PlantCategory.Succulents,
    native: false,
    nativeDetails: "Naturalised (European)",
    foliage: FoliageType.Evergreen,
    dimensions: "5–10 cm × 15 cm",
    appearance: "Rosettes of fleshy leaves; red or pink summer flowers",
    conditions: "Full sun; free-draining gritty compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Gritty],
    ecologicalImportance: "Provides nectar for pollinators; drought tolerance"
  },
  {
    id: "stonecrop",
    name: "Stonecrop",
    scientificName: "Sedum acre",
    category: PlantCategory.Succulents,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "5–15 cm × 25 cm",
    appearance: "Tiny green leaves and clusters of yellow flowers",
    conditions: "Full sun; very free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Gritty],
    ecologicalImportance: "Attracts pollinators and tolerates poor soils"
  },
  {
    id: "jelly-bean-plant",
    name: "Jelly Bean Plant",
    scientificName: "Sedum × rubrotinctum",
    category: PlantCategory.Succulents,
    native: false,
    nativeDetails: "No – Mexico",
    foliage: FoliageType.Evergreen,
    dimensions: "15 cm × 25 cm",
    appearance: "Red-tipped, fleshy leaves and yellow flowers",
    conditions: "Full sun, minimal watering",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Gritty, SoilType.WellDrained],
    ecologicalImportance: "Ideal for water-efficient container planting"
  },
  {
    id: "coopers-ice-plant",
    name: "Cooper’s Ice Plant",
    scientificName: "Delosperma cooperi",
    category: PlantCategory.Succulents,
    native: false,
    nativeDetails: "No – South Africa",
    foliage: FoliageType.Evergreen,
    dimensions: "10–15 cm × 45 cm",
    appearance: "Succulent green leaves; bright magenta daisy-like flowers",
    conditions: "Full sun; gritty, free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Gritty, SoilType.WellDrained],
    ecologicalImportance: "Excellent for bees and butterflies; copes well with dry conditions"
  },
  {
    id: "caucasian-stonecrop",
    name: "Caucasian Stonecrop",
    scientificName: "Sedum spurium",
    category: PlantCategory.Succulents,
    native: false,
    nativeDetails: "No – Caucasus",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "5–10 cm × 30 cm",
    appearance: "Mat-forming, succulent leaves; starry pink or red flowers",
    conditions: "Full sun; free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Popular with bees; thrives on green roofs and containers"
  },
  {
    id: "mexican-snow-ball",
    name: "Mexican Snow Ball",
    scientificName: "Echeveria elegans",
    category: PlantCategory.Succulents,
    native: false,
    nativeDetails: "No – Mexico",
    foliage: FoliageType.Evergreen,
    dimensions: "5–20 cm × 15 cm",
    appearance: "Compact, blue-grey rosettes; pink flowers on upright stems",
    conditions: "Full sun; well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Good for container gardens; attracts pollinators in summer"
  },

  // LIST 5, 9, 10: Bulbs
  {
    id: "english-bluebell",
    name: "English Bluebell",
    scientificName: "Hyacinthoides non-scripta",
    category: PlantCategory.BulbsSpring,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "40 cm × 15 cm",
    appearance: "Arching stems with nodding, blue bell-shaped flowers",
    conditions: "Dappled shade, moist but well-drained soil",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Early spring nectar for bees"
  },
  {
    id: "snowdrop",
    name: "Snowdrop",
    scientificName: "Galanthus nivalis",
    category: PlantCategory.BulbsSpring,
    native: false,
    nativeDetails: "Naturalised",
    foliage: FoliageType.Deciduous,
    dimensions: "10–15 cm × 5 cm",
    appearance: "Delicate white, nodding flowers appearing in late winter",
    conditions: "Moist but well-drained soil in partial shade",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Early forage for pollinators"
  },
  {
    id: "crocus",
    name: "Crocus",
    scientificName: "Crocus vernus",
    category: PlantCategory.BulbsSpring,
    native: false,
    nativeDetails: "No – European origin",
    foliage: FoliageType.Deciduous,
    dimensions: "10–15 cm × 10 cm",
    appearance: "Bright purple, yellow, or white goblet-shaped flowers",
    conditions: "Sun or light shade; well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Early nectar source for bees and hoverflies"
  },
  {
    id: "wild-daffodil",
    name: "Wild Daffodil",
    scientificName: "Narcissus pseudonarcissus",
    category: PlantCategory.BulbsSpring,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "40 cm × 15 cm",
    appearance: "Pale yellow, nodding flowers in early spring",
    conditions: "Full sun or partial shade; well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Supports early bees and hoverflies"
  },
  {
    id: "garden-tulip",
    name: "Tulip",
    scientificName: "Tulipa spp.",
    category: PlantCategory.BulbsSpring,
    native: false,
    nativeDetails: "No – Central Asia and Middle East",
    foliage: FoliageType.Deciduous,
    dimensions: "20–50 cm × 10 cm",
    appearance: "Upright, brightly coloured flowers in many forms",
    conditions: "Full sun; rich, well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Fertile],
    ecologicalImportance: "Valuable for pollinators; provides vibrant seasonal impact"
  },
  {
    id: "snake-head-fritillary",
    name: "Snake’s-head Fritillary",
    scientificName: "Fritillaria meleagris",
    category: PlantCategory.BulbsSpring,
    native: true,
    nativeDetails: "Yes (rare)",
    foliage: FoliageType.Deciduous,
    dimensions: "30 cm × 10 cm",
    appearance: "Distinctive chequered purple or white flowers",
    conditions: "Damp, fertile soil in partial shade",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.Fertile],
    ecologicalImportance: "Valuable early food for pollinators"
  },
  {
    id: "wild-tulip",
    name: "Wild Tulip",
    scientificName: "Tulipa sylvestris",
    category: PlantCategory.BulbsSpring,
    native: false,
    nativeDetails: "Naturalised in Britain",
    foliage: FoliageType.Deciduous,
    dimensions: "30 cm × 10 cm",
    appearance: "Bright yellow, fragrant flowers in spring",
    conditions: "Full sun; free-draining soil",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Supports solitary bees"
  },
  {
    id: "wood-anemone",
    name: "Wood Anemone",
    scientificName: "Anemonoides nemorosa",
    category: PlantCategory.BulbsSpring,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "20 cm × 20 cm",
    appearance: "White, daisy-like flowers with delicate foliage",
    conditions: "Moist, humus-rich soil; partial shade",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.Fertile],
    ecologicalImportance: "Early nectar and ground cover for woodland insects"
  },
  {
    id: "lesser-celandine",
    name: "Lesser Celandine",
    scientificName: "Ficaria verna",
    category: PlantCategory.BulbsSpring,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "15 cm × 25 cm",
    appearance: "Glossy yellow flowers in early spring",
    conditions: "Moist soil in sun or light shade",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Vital early source of pollen"
  },
  {
    id: "cyclamen-coum",
    name: "Cyclamen",
    scientificName: "Cyclamen coum",
    category: PlantCategory.BulbsSpring,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Deciduous,
    dimensions: "10 cm × 15 cm",
    appearance: "Heart-shaped leaves and pink flowers in winter",
    conditions: "Partial shade, well-drained compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Early nectar source and decorative winter interest"
  },
  {
    id: "grape-hyacinth",
    name: "Grape Hyacinth",
    scientificName: "Muscari armeniacum",
    category: PlantCategory.BulbsSpring,
    native: false,
    nativeDetails: "No – Mediterranean origin",
    foliage: FoliageType.Deciduous,
    dimensions: "15 cm × 10 cm",
    appearance: "Spikes of dense, blue, bell-shaped flowers",
    conditions: "Full sun or partial shade; free-draining compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Spring nectar for bees and hoverflies"
  },
  {
    id: "allium",
    name: "Allium",
    scientificName: "Allium spp.",
    category: PlantCategory.BulbsSummer,
    native: true,
    nativeDetails: "Some species native",
    foliage: FoliageType.Deciduous,
    dimensions: "30–90 cm × 20 cm",
    appearance: "Tall stems topped with globes of purple or white flowers",
    conditions: "Full sun; well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Excellent for bees and butterflies"
  },
  {
    id: "lily",
    name: "Lily",
    scientificName: "Lilium spp.",
    category: PlantCategory.BulbsSummer,
    native: false,
    nativeDetails: "No – Asia, Europe, and North America",
    foliage: FoliageType.Deciduous,
    dimensions: "45–120 cm × 30 cm",
    appearance: "Large, showy, often fragrant flowers in summer",
    conditions: "Sun or light shade; fertile, free-draining compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Attracts night-flying pollinators such as moths"
  },
  {
    id: "gladiolus",
    name: "Gladiolus",
    scientificName: "Gladiolus communis subsp. byzantinus",
    category: PlantCategory.BulbsSummer,
    native: false,
    nativeDetails: "Naturalised in the UK",
    foliage: FoliageType.Deciduous,
    dimensions: "60–90 cm × 15 cm",
    appearance: "Sword-like leaves with spikes of magenta flowers",
    conditions: "Full sun; moderately fertile, well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Fertile],
    ecologicalImportance: "Provides vertical structure and nectar for pollinators"
  },
  {
    id: "autumn-crocus",
    name: "Autumn Crocus",
    scientificName: "Colchicum autumnale",
    category: PlantCategory.BulbsSummer,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "15–25 cm × 10 cm",
    appearance: "Pale lilac flowers emerging after leaves die back",
    conditions: "Moist but well-drained compost; partial shade",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Extends flowering season and provides late nectar"
  },
  {
    id: "cyclamen-hederifolium",
    name: "Cyclamen (Autumn)",
    scientificName: "Cyclamen hederifolium",
    category: PlantCategory.BulbsSummer,
    native: false,
    nativeDetails: "Naturalised in the UK",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "10 cm × 20 cm",
    appearance: "Marbled leaves and pink or white flowers in late summer to autumn",
    conditions: "Partial shade; humus-rich, well-drained compost",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Supports late-season pollinators; decorative winter foliage"
  },

  // LIST 11 & Appendix: Climbers
  {
    id: "hardy-kiwi",
    name: "Hardy Kiwi (Issai)",
    scientificName: "Actinidia arguta ‘Issai’",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – East Asia",
    foliage: FoliageType.Deciduous,
    dimensions: "2–3 m × 1–1.5 m",
    appearance: "Small, fragrant white flowers in early summer; smooth, edible kiwis",
    conditions: "Full sun; fertile, moist but free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Nectar for pollinators; fruit can provide food for birds"
  },
  {
    id: "english-ivy",
    name: "English Ivy (Compact)",
    scientificName: "Hedera helix",
    category: PlantCategory.Climbers,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Evergreen,
    dimensions: "1.5–2.5 m × 1–1.5 m",
    appearance: "Attractive foliage year-round; late-season flowers and berries",
    conditions: "Sun or shade; prefers moist soil",
    lightTags: [LightRequirement.Sun, LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Vital late nectar; berries feed birds"
  },
  {
    id: "climbing-euonymus",
    name: "Climbing Euonymus",
    scientificName: "Euonymus fortunei",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – East Asia",
    foliage: FoliageType.Evergreen,
    dimensions: "1.5–2 m × 0.8–1 m",
    appearance: "Year-round foliage that brightens shade; can be trained to climb",
    conditions: "Sun or shade; fertile, well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.Shade, LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Evergreen shelter for invertebrates"
  },
  {
    id: "purple-bell-vine",
    name: "Purple Bell Vine",
    scientificName: "Rhodochiton atrosanguineus",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – Mexico",
    foliage: FoliageType.Deciduous,
    dimensions: "1.5–2 m × 0.5–0.8 m",
    appearance: "Dramatic purple tubular flowers with maroon dangling bells",
    conditions: "Full sun; fertile, moist compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.Moist],
    ecologicalImportance: "Summer nectar for bees and hoverflies"
  },
  {
    id: "black-eyed-susan",
    name: "Black-eyed Susan Vine",
    scientificName: "Thunbergia alata",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – East Africa",
    foliage: FoliageType.Annual,
    dimensions: "1.5–2 m × 0.5–1 m",
    appearance: "Cheerful yellow/orange flowers with dark eye",
    conditions: "Full sun; fertile, moist but free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Attracts bees and other pollinators"
  },
  {
    id: "cup-and-saucer",
    name: "Cup and Saucer Vine",
    scientificName: "Cobaea scandens",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – Mexico",
    foliage: FoliageType.Deciduous,
    dimensions: "2–3 m × 1–1.5 m",
    appearance: "Distinctive bell-shaped flowers with flared ‘saucer’ calyx",
    conditions: "Full sun to light shade; fertile, moist but well-drained",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile, SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Long flowering period supplies nectar for bees"
  },
  {
    id: "patio-grape",
    name: "Patio Grape",
    scientificName: "Vitis vinifera",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – Europe/Western Asia",
    foliage: FoliageType.Deciduous,
    dimensions: "1.5–2.5 m × 1–1.5 m",
    appearance: "Small fragrant flowers; edible grapes on suitable cultivars",
    conditions: "Full sun; fertile, free-draining compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Flowers attract pollinators; grapes feed birds"
  },
  {
    id: "climbing-nasturtium",
    name: "Climbing Nasturtium",
    scientificName: "Tropaeolum majus",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – South America",
    foliage: FoliageType.Annual,
    dimensions: "1.5–2 m × 0.5–1 m",
    appearance: "Vibrant funnel-shaped flowers in yellow, orange, and red",
    conditions: "Full sun; moderately fertile, well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Excellent nectar for bees, hoverflies, and butterflies"
  },
  {
    id: "himalayan-clematis-compact",
    name: "Himalayan Clematis (Compact)",
    scientificName: "Clematis montana",
    category: PlantCategory.Climbers,
    native: false,
    nativeDetails: "No – Himalayas",
    foliage: FoliageType.Deciduous,
    dimensions: "2–3 m × 1–1.5 m",
    appearance: "Masses of pale pink, scented flowers in late spring",
    conditions: "Sun or partial shade; fertile, moist but well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Fertile, SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Early nectar for bees; nesting cover for small birds"
  },
  {
    id: "clematis-vigorous",
    name: "Clematis (Vigorous)",
    scientificName: "Clematis spp.",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – Mixed origin",
    foliage: FoliageType.Deciduous,
    dimensions: "5–8 m × 1.5–2.5 m",
    appearance: "Climbing vine with abundant star-shaped flowers",
    conditions: "Full sun or partial shade; deep, moist, well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Flowers support bees; cover provides shelter"
  },
  {
    id: "clematis-armandii",
    name: "Clematis armandii",
    scientificName: "Clematis armandii",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – China",
    foliage: FoliageType.Evergreen,
    dimensions: "5–7 m × 1.5–2 m (Container)",
    appearance: "Glossy, leathery leaves; masses of fragrant white starry flowers",
    conditions: "Sheltered, sunny wall; moisture-retentive but free-draining",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Early-season nectar; evergreen cover"
  },
  {
    id: "clematis-cirrhosa",
    name: "Winter-flowering Clematis",
    scientificName: "Clematis cirrhosa",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – Mediterranean",
    foliage: FoliageType.Evergreen,
    dimensions: "3–5 m × 1–1.5 m",
    appearance: "Ferny evergreen leaves; cream to speckled bell-shaped flowers in winter",
    conditions: "Sheltered, sunny or lightly shaded wall; well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Winter flowers valuable for early bees"
  },
  {
    id: "clematis-montana-large",
    name: "Himalayan Clematis (Large)",
    scientificName: "Clematis montana",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – Himalayas",
    foliage: FoliageType.Deciduous,
    dimensions: "5–7 m × 1.5–2 m",
    appearance: "Masses of scented single flowers in spring",
    conditions: "Full sun or partial shade; moisture-retentive soil",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist],
    ecologicalImportance: "Spring flowers benefit pollinators; dense foliage offers cover"
  },
  {
    id: "climbing-rose",
    name: "Climbing Rose",
    scientificName: "Rosa spp.",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – Mixed origin",
    foliage: FoliageType.Deciduous,
    dimensions: "2.5–5 m × 1–1.5 m",
    appearance: "Clusters of scented flowers in a wide colour range",
    conditions: "Full sun; fertile loam-rich compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile],
    ecologicalImportance: "Nectar/pollen for insects; hips for birds"
  },
  {
    id: "star-jasmine",
    name: "Star Jasmine",
    scientificName: "Trachelospermum jasminoides",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – East Asia",
    foliage: FoliageType.Evergreen,
    dimensions: "4–6 m × 1.5–2 m (Container)",
    appearance: "Glossy foliage; highly scented white star-shaped flowers",
    conditions: "Sheltered, sunny wall; fertile, well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Flowers attract bees and night-flying pollinators"
  },
  {
    id: "passion-flower",
    name: "Passion Flower",
    scientificName: "Passiflora caerulea",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – South America",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "4–6 m × 1.5–2 m",
    appearance: "Exotic white and blue flowers with striking filaments",
    conditions: "Full sun in shelter; protect roots in winter",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained, SoilType.Fertile],
    ecologicalImportance: "Nectar and pollen for bees; summer shelter",
    limitations: "Marginal hardiness; root restriction reduces flowering; can become straggly; may die back in severe winters"
  },
  {
    id: "potato-vine",
    name: "Potato Vine",
    scientificName: "Solanum jasminoides",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – South America",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "4–6 m × 1.5–2 m",
    appearance: "Clusters of white or pale blue starry flowers",
    conditions: "Sunny, sheltered wall; well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Flowers attract bees and hoverflies"
  },
  {
    id: "honeysuckle-large",
    name: "Honeysuckle (Climber)",
    scientificName: "Lonicera periclymenum",
    category: PlantCategory.ClimbersLarge,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "3.5–5 m × 1–1.5 m (Container)",
    appearance: "Tubular, often scented flowers in summer; colours range from creamy-white to red",
    conditions: "Full sun or partial shade; moist but well-drained compost; feed regularly",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Strong wildlife value; nectar for moths, bees, and long-tongued pollinators; berries support birds",
    limitations: "Often fails to reach 5 m in containers unless well-fed; mildew-prone; may decline if rootbound"
  },
  {
    id: "evergreen-honeysuckle",
    name: "Evergreen Honeysuckle",
    scientificName: "Lonicera henryi",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – China",
    foliage: FoliageType.Evergreen,
    dimensions: "4–6 m × 1.5–2 m (Container)",
    appearance: "Dark green leaves; tubular yellow-to-red flowers in summer; decorative black berries",
    conditions: "Sun or partial shade; moist, fertile but well-drained compost",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Good wildlife value; flowers feed insects; berries for birds",
    limitations: "Often fails to reach top end of height range in containers; foliage can thin with age or exposure; mildew in dry conditions"
  },
  {
    id: "climbing-hydrangea",
    name: "Climbing Hydrangea",
    scientificName: "Hydrangea anomala subsp. petiolaris",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – Japan, Korea & Russia",
    foliage: FoliageType.Deciduous,
    dimensions: "3–5 m × 1–1.5 m (Container)",
    appearance: "Self-clinging climber with heart-shaped leaves; white lacecap flowers in early summer",
    conditions: "Partial shade; cool, moist but well-drained compost; sheltered site best",
    lightTags: [LightRequirement.PartialShade],
    soilTags: [SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Flowers provide nectar and pollen for insects; foliage provides cover",
    limitations: "Rarely reaches 5 m in pots; weak flowering and growth; slow, often poor long-term performance; best in-ground",
    notRecommended: true
  },
  {
    id: "common-hop",
    name: "Common Hop",
    scientificName: "Humulus lupulus",
    category: PlantCategory.ClimbersLarge,
    native: true,
    nativeDetails: "Yes",
    foliage: FoliageType.Deciduous,
    dimensions: "4–6 m × 1–1.5 m (Container)",
    appearance: "Fast twining climber with coarse stems and lobed leaves; female plants produce hop cones",
    conditions: "Full sun; fertile, moist but well-drained compost; cut to ground in winter",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.Moist, SoilType.WellDrained],
    ecologicalImportance: "Supports caterpillars; nectar for insects; wildlife uses dried stems for shelter",
    limitations: "Dies back each winter leaving bare space; root system quickly fills containers; coarse foliage"
  },
  {
    id: "virginia-creeper",
    name: "Virginia Creeper / Boston Ivy",
    scientificName: "Parthenocissus spp.",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – North America/East Asia",
    foliage: FoliageType.Deciduous,
    dimensions: "5–8 m × 2–3 m (Container, short-term)",
    appearance: "Self-clinging climber with attractive green foliage turning vivid red, orange and purple in autumn",
    conditions: "Sun or partial shade; tolerates most soils; extremely vigorous",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Provides berries for birds and shelter for wildlife",
    limitations: "Rapidly rootbinds and declines after 2–4 years; overly vigorous; adhesive pads damage walls; poor foliage when root-restricted",
    notRecommended: true
  },
  {
    id: "trumpet-vine",
    name: "Trumpet Vine",
    scientificName: "Campsis radicans",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – North America",
    foliage: FoliageType.Deciduous,
    dimensions: "3.5–5 m × 1–2 m (Container)",
    appearance: "Showy orange or red trumpet-shaped flowers in late summer; bold, pinnate leaves",
    conditions: "Full sun; warm, sheltered wall; fertile, well-drained compost",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Flowers attract bees, butterflies and hummingbird hawkmoths",
    limitations: "Rarely flowers reliably in UK containers; requires heat and root-run; prone to dieback in cold winters; poor long-term performance",
    notRecommended: true
  },
  {
    id: "russian-vine",
    name: "Russian Vine",
    scientificName: "Fallopia baldschuanica",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – Central Asia",
    foliage: FoliageType.Deciduous,
    dimensions: "6–8 m × 2–3 m (Container, short-term)",
    appearance: "Extremely fast-growing vine with masses of white to pinkish flowers in late summer",
    conditions: "Full sun; any well-drained compost; drought-tolerant once established",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Late flowers provide nectar for insects",
    limitations: "Excessively vigorous, quickly becomes unmanageable; root-restricts rapidly leading to decline; coarse and untidy",
    notRecommended: true
  },
  {
    id: "wisteria",
    name: "Wisteria",
    scientificName: "Wisteria spp.",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – China, Japan & USA",
    foliage: FoliageType.Deciduous,
    dimensions: "3–5 m × 1.5–2 m (Container)",
    appearance: "Elegant pendulous racemes of scented flowers in spring; architectural vine with woody stems",
    conditions: "Full sun; fertile, well-drained compost; strong support; careful pruning regime required",
    lightTags: [LightRequirement.Sun],
    soilTags: [SoilType.Fertile, SoilType.WellDrained],
    ecologicalImportance: "Flowers visited by bees; structure may provide nesting habitat",
    limitations: "Slow to establish, rarely flowers well in containers; root restriction inhibits flowering; becomes woody and congested",
    notRecommended: true
  },
  {
    id: "chocolate-vine",
    name: "Chocolate Vine",
    scientificName: "Akebia quinata",
    category: PlantCategory.ClimbersLarge,
    native: false,
    nativeDetails: "No – East Asia",
    foliage: FoliageType.SemiEvergreen,
    dimensions: "2–4 m × 1–2 m (Container, short-term)",
    appearance: "Vigorous twining climber with palmate leaves; chocolate-scented purple-brown flowers; unusual fruits",
    conditions: "Prefers full sun to partial shade; tolerates range of soils; requires strong support",
    lightTags: [LightRequirement.Sun, LightRequirement.PartialShade],
    soilTags: [SoilType.WellDrained],
    ecologicalImportance: "Flowers attract early pollinators; dense foliage offers shelter",
    limitations: "Can become invasive; rarely fruits in cooler climates; growth tangles; container performance is often short-lived",
    notRecommended: true
  }
];
